# Generated by Django 3.2.9 on 2021-12-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_status',
            field=models.BooleanField(default=False),
        ),
    ]
