# Generated by Django 3.2.9 on 2021-12-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20211206_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='videofile',
            field=models.FileField(null=True, upload_to='images/{product.id}', verbose_name=''),
        ),
    ]
