<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-12-06 18:04
=======
# Generated by Django 3.2.9 on 2021-12-06 16:55
>>>>>>> c6de6650ca394643be323e8daa9577c133d24e38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('communities', '0003_alter_product_sold_status'),
    ]

    operations = [
    ]
