# Generated by Django 3.2.9 on 2021-12-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('communities', '0003_alter_product_sold_status'),
    ]

    operations = [
    ]
