# Generated by Django 3.2.9 on 2021-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_product_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='videofile',
            field=models.FileField(null=True, upload_to='images/{Product.id}', verbose_name=''),
        ),
    ]
