# Generated by Django 4.0 on 2021-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=50),
        ),
    ]
