# Generated by Django 4.0 on 2021-12-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_basket'),
        ('communities', '0007_alter_membership_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.basket'),
        ),
    ]
