# Generated by Django 4.0 on 2021-12-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_product_basket_id_alter_product_image'),
        ('communities', '0007_alter_membership_member_role'),
    ]

    operations = [
    ]
