# Generated by Django 3.2.9 on 2021-12-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
