# Generated by Django 4.0 on 2021-12-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_basket'),
        ('members', '0004_delete_request'),
    ]

    operations = [
    ]
