# Generated by Django 4.0 on 2021-12-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_merge_0003_basket_0004_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='authcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sharedId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
